[package]
name = "ssdcg"
version = "0.2.3"
edition = "2021"
license-file = "LICENSE"
description = "A service and data description format + a code generator based on rhai scripts"
homepage = "https://github.com/hardliner66/ssdcg"
repository = "https://github.com/hardliner66/ssdcg"
readme = "README.md"

[dependencies]
anyhow = "1.0.56"
derive_more = "0.99.17"
getset = "0.1.2"
glob = "0.3.0"
insta = { version = "1.21.1", features = ["ron"] }
lazy_static = "1.4.0"
permissions = "0.3.0"
pest = "2.1.3"
pest_derive = "2.1.0"
regex = "1.5.5"
rhai = "1.5.0"
ron = "0.8.0"
serde = { version = "1.0.147", features = ["derive"] }
shellexpand = "2.1.0"
structopt = "0.3.26"
